services:
  alert-agent:
    build:
      context: .
      platforms:
        - linux/amd64
    platform: linux/amd64
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      PROMETHEUS_URL: ${PROMETHEUS_URL}
      LOKI_URL: ${LOKI_URL}
      LOGS_DIR: /app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
