apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dai-mongo
  namespace: monitoring
spec:
  serviceName: dai-mongo
  replicas: 1
  selector:
    matchLabels:
      app: dai-mongo
  template:
    metadata:
      labels:
        app: dai-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dai-mongo
  namespace: monitoring
spec:
  selector:
    app: dai-mongo
  ports:
    - port: 27017
      targetPort: 27017
